AGENCY_CODE = 'AGENCY_CODE'
LOGIN_AGENT = 'login_agent'
PASSWORD_AGENT = 'password_agent'

SERVICE_CODES = [
    ("PAIEMENTMARCHANDOMPAYCIDIRECT", "PAIEMENTMARCHANDOMPAYCIDIRECT")
]

TRANSACTION_STATUS = [
    ("pending", "PENDING"),
    ("success", "SUCCESS"),
    ("failed", "FAILED")
]
